// src/lib/mockData/products.ts

import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: {
      uz: "Paracetamol 500mg",
      ru: "Парацетамол 500мг",
      en: "Paracetamol 500mg",
    },
    description: {
      uz: "Paracetamol og'riq qoldiruvchi va isitmani tushiruvchi doridir. Bosh og'rig'i, tish og'rig'i, mushak og'rig'i va shamollash bilan bog'liq alomatlarni davolash uchun ishlatiladi.",
      ru: "Парацетамол - обезболивающее и жаропонижающее средство. Применяется для лечения головной боли, зубной боли, мышечной боли и симптомов простуды.",
      en: "Paracetamol is a pain reliever and fever reducer. Used to treat headaches, toothaches, muscle pain, and cold symptoms.",
    },
    shortDescription: {
      uz: "Og'riq qoldiruvchi va isitma tushiruvchi",
      ru: "Обезболивающее и жаропонижающее",
      en: "Pain reliever and fever reducer",
    },
    price: 15000,
    originalPrice: 20000,
    discount: 25,
    images: [
      "/images/products/paracetamol-1.jpg",
      "/images/products/paracetamol-2.jpg",
    ],
    category: "Og'riq qoldiruvchilar",
    categorySlug: "pain-relievers",
    brand: "Pharmstandard",
    inStock: true,
    stockCount: 150,
    rating: 4.5,
    reviewCount: 89,
    tags: ["og'riq", "isitma", "bosh og'rig'i"],
    featured: true,
    bestseller: true,
    isNew: false,
    prescription: false,
    manufacturer: {
      uz: "Pharmstandard",
      ru: "Фармстандарт",
      en: "Pharmstandard",
    },
    country: {
      uz: "Rossiya",
      ru: "Россия",
      en: "Russia",
    },
    dosage: {
      uz: "500mg tabletkalar",
      ru: "500мг таблетки",
      en: "500mg tablets",
    },
    form: {
      uz: "Tabletkalar",
      ru: "Таблетки",
      en: "Tablets",
    },
    activeIngredient: {
      uz: "Paracetamol",
      ru: "Парацетамол",
      en: "Paracetamol",
    },
    usage: {
      uz: "Kattalar va 12 yoshdan katta bolalar uchun: 1-2 tabletka kuniga 3-4 marta. Maksimal kunlik doza 4g.",
      ru: "Взрослые и дети старше 12 лет: 1-2 таблетки 3-4 раза в день. Максимальная суточная доза 4г.",
      en: "Adults and children over 12: 1-2 tablets 3-4 times daily. Maximum daily dose 4g.",
    },
    storage: {
      uz: "25°C dan past haroratda saqlang",
      ru: "Хранить при температуре ниже 25°C",
      en: "Store below 25°C",
    },
  },
  {
    id: "2",
    name: {
      uz: "Vitamin D3 2000 IU",
      ru: "Витамин D3 2000 МЕ",
      en: "Vitamin D3 2000 IU",
    },
    description: {
      uz: "Vitamin D3 suyak sog'lig'ini qo'llab-quvvatlaydi va immunitetni mustahkamlaydi. Kaltsiy so'rilishini yaxshilaydi va suyak zichligini saqlashga yordam beradi.",
      ru: "Витамин D3 поддерживает здоровье костей и укрепляет иммунитет. Улучшает усвоение кальция и помогает поддерживать плотность костей.",
      en: "Vitamin D3 supports bone health and strengthens immunity. Improves calcium absorption and helps maintain bone density.",
    },
    shortDescription: {
      uz: "Suyak va immunitet uchun",
      ru: "Для костей и иммунитета",
      en: "For bones and immunity",
    },
    price: 45000,
    images: ["/images/products/vitamin-d3-1.jpg"],
    category: "Vitaminlar va minerallar",
    categorySlug: "vitamins",
    brand: "Solgar",
    inStock: true,
    stockCount: 80,
    rating: 4.8,
    reviewCount: 156,
    tags: ["vitamin", "immunitet", "suyak"],
    featured: true,
    bestseller: true,
    isNew: false,
    prescription: false,
    manufacturer: {
      uz: "Solgar",
      ru: "Солгар",
      en: "Solgar",
    },
    country: {
      uz: "AQSh",
      ru: "США",
      en: "USA",
    },
    dosage: {
      uz: "2000 IU kapsulalar",
      ru: "2000 МЕ капсулы",
      en: "2000 IU capsules",
    },
    form: {
      uz: "Yumshoq kapsulalar",
      ru: "Мягкие капсулы",
      en: "Soft capsules",
    },
    usage: {
      uz: "Kuniga 1 kapsula ovqat bilan",
      ru: "1 капсула в день с едой",
      en: "1 capsule daily with food",
    },
  },
  {
    id: "3",
    name: {
      uz: "Aspirin 100mg",
      ru: "Аспирин 100мг",
      en: "Aspirin 100mg",
    },
    description: {
      uz: "Aspirin qon ivishini kamaytiradi va yurak-qon tomir kasalliklarining oldini olishga yordam beradi. Yurak xuruji va insult xavfini kamaytiradi.",
      ru: "Аспирин разжижает кровь и помогает предотвратить сердечно-сосудистые заболевания. Снижает риск инфаркта и инсульта.",
      en: "Aspirin thins blood and helps prevent cardiovascular diseases. Reduces risk of heart attack and stroke.",
    },
    shortDescription: {
      uz: "Yurak-qon tomir uchun",
      ru: "Для сердечно-сосудистой системы",
      en: "For cardiovascular system",
    },
    price: 12000,
    images: ["/images/products/aspirin-1.jpg"],
    category: "Yurak-qon tomir",
    categorySlug: "cardiovascular",
    brand: "Bayer",
    inStock: true,
    stockCount: 200,
    rating: 4.6,
    reviewCount: 234,
    tags: ["yurak", "qon tomir", "profilaktika"],
    featured: false,
    bestseller: true,
    isNew: false,
    prescription: true,
    manufacturer: {
      uz: "Bayer",
      ru: "Байер",
      en: "Bayer",
    },
    country: {
      uz: "Germaniya",
      ru: "Германия",
      en: "Germany",
    },
  },
  {
    id: "4",
    name: {
      uz: "Omega-3 1000mg",
      ru: "Омега-3 1000мг",
      en: "Omega-3 1000mg",
    },
    description: {
      uz: "Omega-3 yog' kislotalari yurak sog'lig'ini qo'llab-quvvatlaydi, miyaning funktsiyasini yaxshilaydi va yallig'lanishni kamaytiradi.",
      ru: "Омега-3 жирные кислоты поддерживают здоровье сердца, улучшают функцию мозга и уменьшают воспаление.",
      en: "Omega-3 fatty acids support heart health, improve brain function and reduce inflammation.",
    },
    shortDescription: {
      uz: "Yurak va miya uchun",
      ru: "Для сердца и мозга",
      en: "For heart and brain",
    },
    price: 85000,
    originalPrice: 95000,
    discount: 11,
    images: ["/images/products/omega3-1.jpg"],
    category: "Vitaminlar va minerallar",
    categorySlug: "vitamins",
    brand: "Nordic Naturals",
    inStock: true,
    stockCount: 45,
    rating: 4.9,
    reviewCount: 312,
    tags: ["omega-3", "yurak", "miya"],
    featured: true,
    bestseller: true,
    isNew: true,
    prescription: false,
    manufacturer: {
      uz: "Nordic Naturals",
      ru: "Нордик Натуралс",
      en: "Nordic Naturals",
    },
    country: {
      uz: "Norvegiya",
      ru: "Норвегия",
      en: "Norway",
    },
  },
  {
    id: "5",
    name: {
      uz: "Probiotiklar Complex",
      ru: "Пробиотики Комплекс",
      en: "Probiotics Complex",
    },
    description: {
      uz: "Probiotiklar hazm sistemasini qo'llab-quvvatlaydi va immun tizimini mustahkamlaydi. Ichak mikroflorasini tiklaydi.",
      ru: "Пробиотики поддерживают пищеварительную систему и укрепляют иммунную систему. Восстанавливают микрофлору кишечника.",
      en: "Probiotics support digestive system and strengthen immune system. Restore intestinal microflora.",
    },
    shortDescription: {
      uz: "Hazm va immunitet uchun",
      ru: "Для пищеварения и иммунитета",
      en: "For digestion and immunity",
    },
    price: 120000,
    images: ["/images/products/probiotics-1.jpg"],
    category: "Hazm tizimi",
    categorySlug: "digestive",
    brand: "Garden of Life",
    inStock: true,
    stockCount: 30,
    rating: 4.7,
    reviewCount: 178,
    tags: ["probiotik", "hazm", "immunitet"],
    featured: false,
    bestseller: true,
    isNew: false,
    prescription: false,
    manufacturer: {
      uz: "Garden of Life",
      ru: "Гарден оф Лайф",
      en: "Garden of Life",
    },
    country: {
      uz: "AQSh",
      ru: "США",
      en: "USA",
    },
  },
  {
    id: "6",
    name: {
      uz: "Magniy B6 Forte",
      ru: "Магний B6 Форте",
      en: "Magnesium B6 Forte",
    },
    description: {
      uz: "Magniy va B6 vitamini stress va charchoqni kamaytiradi, uyqu sifatini yaxshilaydi va nerv tizimini qo'llab-quvvatlaydi.",
      ru: "Магний и витамин B6 снижают стресс и усталость, улучшают качество сна и поддерживают нервную систему.",
      en: "Magnesium and vitamin B6 reduce stress and fatigue, improve sleep quality and support nervous system.",
    },
    shortDescription: {
      uz: "Stress va uyqu uchun",
      ru: "Для стресса и сна",
      en: "For stress and sleep",
    },
    price: 35000,
    images: ["/images/products/magnesium-b6-1.jpg"],
    category: "Vitaminlar va minerallar",
    categorySlug: "vitamins",
    brand: "Evalar",
    inStock: true,
    stockCount: 120,
    rating: 4.5,
    reviewCount: 98,
    tags: ["magniy", "stress", "uyqu"],
    featured: false,
    bestseller: true,
    isNew: false,
    prescription: false,
    manufacturer: {
      uz: "Evalar",
      ru: "Эвалар",
      en: "Evalar",
    },
    country: {
      uz: "Rossiya",
      ru: "Россия",
      en: "Russia",
    },
  },
  {
    id: "7",
    name: {
      uz: "Vitamin C 1000mg",
      ru: "Витамин C 1000мг",
      en: "Vitamin C 1000mg",
    },
    description: {
      uz: "Vitamin C kuchli antioksidant bo'lib, immunitetni mustahkamlaydi va shamollash bilan kurashishga yordam beradi.",
      ru: "Витамин C - мощный антиоксидант, укрепляет иммунитет и помогает бороться с простудой.",
      en: "Vitamin C is a powerful antioxidant that strengthens immunity and helps fight colds.",
    },
    shortDescription: {
      uz: "Immunitet uchun",
      ru: "Для иммунитета",
      en: "For immunity",
    },
    price: 28000,
    images: ["/images/products/vitamin-c-1.jpg"],
    category: "Vitaminlar va minerallar",
    categorySlug: "vitamins",
    brand: "Now Foods",
    inStock: true,
    stockCount: 95,
    rating: 4.6,
    reviewCount: 145,
    tags: ["vitamin", "immunitet", "antioksidant"],
    featured: false,
    bestseller: false,
    isNew: true,
    prescription: false,
    manufacturer: {
      uz: "Now Foods",
      ru: "Нау Фудс",
      en: "Now Foods",
    },
    country: {
      uz: "AQSh",
      ru: "США",
      en: "USA",
    },
  },
  {
    id: "8",
    name: {
      uz: "Kollagen Peptidlar",
      ru: "Коллаген Пептиды",
      en: "Collagen Peptides",
    },
    description: {
      uz: "Kollagen teri elastikligini yaxshilaydi, bo'g'im sog'lig'ini qo'llab-quvvatlaydi va soch va tirnoqlarni mustahkamlaydi.",
      ru: "Коллаген улучшает эластичность кожи, поддерживает здоровье суставов и укрепляет волосы и ногти.",
      en: "Collagen improves skin elasticity, supports joint health and strengthens hair and nails.",
    },
    shortDescription: {
      uz: "Teri va bo'g'imlar uchun",
      ru: "Для кожи и суставов",
      en: "For skin and joints",
    },
    price: 150000,
    originalPrice: 180000,
    discount: 17,
    images: ["/images/products/collagen-1.jpg"],
    category: "Go'zallik va parvarish",
    categorySlug: "beauty",
    brand: "Vital Proteins",
    inStock: true,
    stockCount: 25,
    rating: 4.8,
    reviewCount: 267,
    tags: ["kollagen", "teri", "bo'g'im"],
    featured: true,
    bestseller: false,
    isNew: true,
    prescription: false,
    manufacturer: {
      uz: "Vital Proteins",
      ru: "Витал Протеинс",
      en: "Vital Proteins",
    },
    country: {
      uz: "AQSh",
      ru: "США",
      en: "USA",
    },
  },
];
